### ISSUE TITLE
`Error: trying to commit when not checkpointed` on runBlock

### ISSUE THREAD

**Issue by asinyagin** [ethereum/ethereumjs-vm#10]
Hey,

I've updated ethereumjs libs and now I'm getting the error:
```
/home/user/ethereum-sandbox/node_modules/merkle-patricia-tree/checkpoint-interface.js:57
      throw new Error('trying to commit when not checkpointed')
            ^
Error: trying to commit when not checkpointed
    at /home/user/ethereum-sandbox/node_modules/merkle-patricia-tree/checkpoint-interface.js:57:13
    at Object.item.task (/home/user/ethereum-sandbox/node_modules/merkle-patricia-tree/node_modules/semaphore/lib/semaphore.js:24:29)
    at Object.semaphore.take (/home/user/ethereum-sandbox/node_modules/merkle-patricia-tree/node_modules/semaphore/lib/semaphore.js:31:9)
    at Trie.commit (/home/user/ethereum-sandbox/node_modules/merkle-patricia-tree/checkpoint-interface.js:48:12)
    at /home/user/ethereum-sandbox/node_modules/ethereumjs-vm/lib/runTx.js:149:16
    at /home/user/ethereum-sandbox/node_modules/async/lib/async.js:187:20
    at /home/user/ethereum-sandbox/node_modules/async/lib/async.js:239:13
    at _arrayEach (/home/user/ethereum-sandbox/node_modules/async/lib/async.js:91:13)
    at _each (/home/user/ethereum-sandbox/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/home/user/ethereum-sandbox/node_modules/async/lib/async.js:238:9)
```

With that code:
```
      async.series([
        this.vm.runBlock.bind(this.vm, {
          blockchain: this.blockchain,
          block: block,
          generate: true
        }),
        this.blockchain.putBlock.bind(this.blockchain, block)
      ], (function(err, results) {
```

I can't figure out why. Can you help me with this?

**Comment by wanderer** [comment]
@asinyagin please try lastest on the master branch
